export const hotel = {
  Rooms: [
    {
      id: 1,
      name: '101',
      capacity: 2,
      hotelId: 1,
      vacancies: 0,
      Booking: [{ id: 1 }, { id: 2 }],
    },
    {
      id: 2,
      name: '102',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 3,
      name: '103',
      capacity: 3,
      hotelId: 1,
      vacancies: 1,
      Booking: [{ id: 3 }, { id: 4 }],
    },
    {
      id: 4,
      name: '104',
      capacity: 1,
      hotelId: 1,
      vacancies: 0,
      Booking: [{ id: 1 }],
    },
    {
      id: 5,
      name: '105',
      capacity: 2,
      hotelId: 1,
      vacancies: 2,
      Booking: [],
    },
    {
      id: 6,
      name: '106',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 7,
      name: '107',
      capacity: 2,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 8,
      name: '108',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 9,
      name: '109',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 10,
      name: '110',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 11,
      name: '111',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 12,
      name: '112',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 13,
      name: '113',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 14,
      name: '114',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 15,
      name: '115',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
    {
      id: 16,
      name: '116',
      capacity: 1,
      hotelId: 1,
      vacancies: 1,
      Booking: [],
    },
  ],
};
